# .github/workflows/publish.yml
name: Publish Packages

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write # 패키지 발행을 위해 필요

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm' # <-- 이 옵션이 pnpm 설치와 캐싱을 모두 처리합니다.

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all packages
        run: pnpm build

      - name: Publish Packages
        run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
